### ISSUE TITLE
Tile borders when rendering RGB images

### ISSUE THREAD

**Issue by na9da** [hongfaqiu/TIFFImageryProvider#41]
Hi @hongfaqiu 

Thank you for your amazing work in developing this package.

I was testing the latest release `v2.14.1` for integrating with TerriaJS and was wondering if something changed for RGB rendering. I can see that previously, it used to [resample RGB values](https://github.com/hongfaqiu/TIFFImageryProvider/blob/b077cb9d59bd20cc331480da34748c626214d99e/packages/TIFFImageryProvider/src/TIFFImageryProvider.ts#L605) using linear/bi-linear algorithm, but now the resampling works only for [single band images](https://github.com/hongfaqiu/TIFFImageryProvider/blob/98a51f8d9e84194a1f48cab5cec43a0aa3c940f8/packages/TIFFImageryProvider/src/TIFFImageryProvider.ts#L663).

RGB rendering also seems to have some artifacts along tile border. Here's a screenshot from the example app before and after. The before is a build from [this commit](https://github.com/hongfaqiu/TIFFImageryProvider/tree/b077cb9d59bd20cc331480da34748c626214d99e) (v2.13.1) and after is a build from v2.14.1.

![image](https://github.com/user-attachments/assets/9f0c2408-5587-46f1-8a71-f87505d00e4c)
(before, with default linear sampling - tile boundaries are smooth)

![image](https://github.com/user-attachments/assets/917cdb49-48a3-4b37-bf5c-6f9ebfd4413d)
(after - tile boundaries have a cut)

Here's a sample RGB TIFF - https://storage.googleapis.com/rpg-public-cogs/ManningParkLookout1Small20230221_COG.tif
although, I could repro it with any RGB TIFF.

Let me know if you need any additional info.

Cheers,
Nanda

**Comment by hongfaqiu** [comment]
Thank you for your feedback. I have found this problem and it is expected to be solved in the near future.

**Comment by hongfaqiu** [comment]
@na9da It has been fixed. Now plot is used for rgb rendering, and two interpolation methods are supported. The boundary problem has also been resolved. Please check the effect.

**Comment by na9da** [comment]
Hi @hongfaqiu,

Thanks for the speedy fix. That `nearest` sampling now works perfectly.

However, I just wanted to point out that it introduces some new artifacts with `bilinear` sampling - although it also fixes some other artifacts from previous version.

![image](https://github.com/user-attachments/assets/84cdedff-e1d6-407d-a0d5-83213fdba46d)
(now)

![image](https://github.com/user-attachments/assets/7b0ba0e2-c9bd-49ea-9e31-543a3c985ade)
(before)

Is that something you will be able to fix?

**Comment by hongfaqiu** [comment]
@na9da Thanks for your feedback. I will check it when I have time. As shown in your picture, there are indeed some strange pixel behaviors.

**Comment by hongfaqiu** [comment]
@na9da fixed, it's smooth now. Please check again.

![image](https://github.com/user-attachments/assets/30087a6c-33ee-4367-85d0-00873e0cdf26)

**Comment by na9da** [comment]
hmm.. that's interesting. I'm still getting the previous stripes. Not sure if my set up is somehow different from yours :thinking:. Here's a screenshot from the example app.

![image](https://github.com/user-attachments/assets/09f97896-b77a-4e81-9be1-c572453f5254)

Also sharing a [test link](http://ci.terria.io/test-tiff-upgrade/#share=s-bjDxPiid0P22EDJLWjcjCKuNllo&clean&https://gist.githubusercontent.com/na9da/18ce40ab4d93a722932c3efe5c947139/raw/b06ed050745f57ba9b081e7700e6504ea6719a9b/cogs.json) from terria with the latest version of imagery provider.

**Comment by hongfaqiu** [comment]
@na9da Everything is normal on my computer. The configuration is 
Windows, Chrome 131.0.6778.71, and AMD R7 7840H.

![image](https://github.com/user-attachments/assets/04776938-6191-4c63-a6cb-1802bfd6daa6)

**Comment by na9da** [comment]
Ah I see, i'll need to test on a different machine - thanks for checking.

**Comment by na9da** [comment]
You are right, it renders smoothly in Windows. So there must be some WebGL/device related issue?

The [above one I posted](https://github.com/hongfaqiu/TIFFImageryProvider/issues/41#issuecomment-2489922772) is from Linux/Firefox 131.0.3 (but I can repro in Chrome as well).

I also see a slightly different pattern of stripes in Mac OS 15.01, Chrome 130.0.6723.91

![image](https://github.com/user-attachments/assets/5722ab4f-acd6-47c5-acd3-7a86098de597)

Not familiar myself with shader code, but I can try debugging.

**Comment by hongfaqiu** [comment]
This is interesting. As you said, it should be a compatibility issue with WebGL. I will debug it to make it have the same effect on different devices (currently, the rendering effect cannot be seen on mobile phones).
